version: '3'

services:
  db:
    image: postgres
    ports:
      - 5432:5432
    env_file:
      - "local.env"
  redis:
    image: redis
    ports:
      - 6379:6379
  geo:
    image: workivate/geoip-api
    ports:
      - 8080:8080
  flower:
    image: mher/flower
    ports:
      - 5555:5555
    depends_on:
      - redis
    env_file:
      - local.env
  web:
    build: .
    command: >
      sh -c "python3 wait_for_postgres.py &&
             python3 manage.py migrate &&
             python3 manage.py test --noinput &&
             python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    env_file:
      - "local.env"
  celery:
    build: .
    command: celery -A event_target worker -l info
    volumes:
      - .:/app
    depends_on:
      - db
      - geo
      - redis
      - web
    env_file:
      - "local.env"
