# Generated by Django 2.1.4 on 2018-12-08 15:16

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('source_ip', models.GenericIPAddressField()),
                ('name', models.TextField()),
                ('city', models.TextField()),
                ('country_iso', models.TextField()),
                ('country_name', models.TextField()),
                ('latitude', models.TextField()),
                ('longitude', models.TextField()),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
